import type { Metadata } from "next";
import localFont from 'next/font/local';
import NavigationBar from './_components/NavigationBar';
import './globals.css';

const fontB612 = localFont({
	src: '../public/fonts/B612_Mono/B612Mono-Regular.ttf',
	variable: '--font-B612',
	weight: '400',
	style: 'normal',
});

export const metadata: Metadata = {
	title: 'Portfolio | Julien BIGOT',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className={fontB612.className}
		>
			<body className='flex relative'>
				<NavigationBar></NavigationBar>
				{children}
			</body>
		</html>
	);
}

